const projectData = [
  {
    title: "Tech Investment",
    demo: "https://joujou144.github.io/silverback/",
    source: "https://github.com/joujou144/silverback",
    image: "./images/portfolio/silverback.png",
    desc: "A two-page interactive website with simple animation for a potential tech investment client.",
    html: "HTML",
    css: "CSS",
    js: "JavaScript",
  },
  {
    title: "Personal Dahsboard",
    demo: "https://joujou144.github.io/personal-dashboard/",
    source: "https://github.com/joujou144/personal-dashboard",
    image: "./images/portfolio/Personal-Momentum-Dahsboard4.png",
    desc: "Page is rendered dynamically using crypto API, Unsplash images API, local time stamp and geolocation.",
    html: "HTML",
    css: "CSS",
    api: "API",
    js: "JavaScript",
  },
  {
    title: 'My Portfolio',
    demo: "https://github.com/joujou144/AZNIMRAHMAN-Web-Dev-Apprentice",
    source: "https://github.com/joujou144/AZNIMRAHMAN-Web-Dev-Apprentice",
    image: "./images/portfolio/portfolio-site.png",
    desc: "This is the second version of my portfolio. Keeping the code basic but the site remains interactive done with vanilla JS and CSS.",
    html: "HTML",
    css: "CSS",
    js: "JavaScript",
  },
  {
    title: 'Movie Watchlist App',
    demo: "https://joujou144.github.io/movie-watchlist-app/",
    source: "https://github.com/joujou144/movie-watchlist-app",
    image: "./images/portfolio/movie-search-app.png",
    desc: "A 2-page movie watchlist site using JS modules and OMdb API. User can also add and remove favourite movies on a list.",
    html: "HTML",
    css: "CSS",
    api: "API",
    js: "JavaScript",
  },
  {
    title: 'Abundent',
    demo: "https://abundent.com/",
    image: "./images/portfolio/Abundent-New-Website.png",
    desc: "Rebranding main website for a Malaysia's IT corporate organisation. Designed by in-house UX team. Completion status - In progress.",
    html: "HTML",
    css: "CSS",
    js: "JavaScript",
  },
  {
    title: 'Calendar Widget',
    demo: "https://joujou144.github.io/JS-calendar/",
    source: "https://github.com/joujou144/JS-calendar",
    image: "./images/portfolio/Calendar-Widget.png",
    desc: "Solo project using CSS and vanilla JS. Calendar dates, month and year display are rendered dynamically using for loops.",
    html: "HTML",
    css: "CSS",
    js: "JavaScript",
  },


]

export { projectData }